= My Project
firstname lastname
1.0.0, {docdate}: Some notes
ifndef::imagesdir[:imagesdir: images]
//:toc-placement!:  // prevents the generation of the doc at this position, so it can be printed afterwards
:sourcedir: ../src/main/java
:icons: font
:sectnums:    // Nummerierung der Überschriften / section numbering
:toc: left

//Need this blank line after ifdef, don't know why...
ifdef::backend-html5[]

// https://fontawesome.com/v4.7.0/icons/
icon:file-text-o[link=https://raw.githubusercontent.com/htl-leonding-college/asciidoctor-docker-template/master/asciidocs/{docname}.adoc] ‏ ‏ ‎
icon:github-square[link=https://github.com/htl-leonding-college/asciidoctor-docker-template] ‏ ‏ ‎
icon:home[link=https://htl-leonding.github.io/]
endif::backend-html5[]

// print the toc here (not at the default position)
//toc::[]

== Pflichtenheft "Was mache ich"


=== Ausgangssituation

Menschen sind in Gefahr, wenn sie verfolgt werden oder Angst haben, dass ihnen etwas passieren könnte wenn sie zb. in der Nacht auf dem Nachhauseweg sind.
Deswegen soll eine Handy-Applikation entiwckelt werden, die in solchen Situationen hilft.
Die Applikation soll in der Lage sein, die Position des Benutzers zu bestimmen und im Notfall die Polizei zu verständigen.


=== Istzustand
----
Beschreibung der speziellen Situation zB in der Abteilung
----

Bestehende Applikationen, die in solchen Situationen helfen, sind oft nicht ausreichend oder nicht benutzerfreundlich genug.

=== Problemstellung



=== Aufgabenstellung

- Die Applikation soll in der Lage sein, die Position des Benutzers zu bestimmen.
- Die Applikation soll im Notfall die Polizei verständigen.
- Die Applikation soll einfach zu bedienen sein - auch in Stresssituationen.
- Shortcut um der Person am anderen Ende der Leitung zu sagen, dass die Person gerade in Gefahr sein könnte.

==== Funktionale Anforderungen

[plantuml,wireframe,png]
----
@startsalt
{
Name         | "                 "
Modifiers:   | { (X) public | () default | () private | () protected
	            [] abstract | [] final   | [] static }
Superclass:  | { "java.lang.Object " | [Browse...] }
}
@endsalt
----
==== Nichtfunktionale Anforderungen (NFA)
=== Ziele
Die Sicherheit jewilger Menschen gewährleisten. Sofortige aktion und Reaktion auf Gefahrensituationen.

=== Mengengerüst
=== Rahmenbedingungen
zB Vorgaben vom Auftraggeber

== Entwurf "Wie mache ich es"
=== Systemarchitektur
=== ...

== Projekthandbuch "Organisatorische Rahmenbedingungen"



=== GANTT-Diagramm

mit User-Stories (definiert in YouTrack)

[plantuml,gantt-protoype,png]
----
@startgantt
[Test prototype] lasts 10 days
[Prototype completed] happens at [Test prototype]'s end
[Setup assembly line] lasts 12 days
[Setup assembly line] starts at [Test prototype]'s end
[Test prototype 2] lasts 3 days
[Test prototype 2] starts at [Prototype completed]'s end
@endgantt
----



* link:minutes-of-meeting.html[Protokollvorlage]
* link:demo.html[Demo]

